export const MEDICAL_SPECIALTIES = [
  { value: 'allergy', label: 'Allergy & Immunology' },
  { value: 'anesthesiology', label: 'Anesthesiology' },
  { value: 'cardiology', label: 'Cardiology' },
  { value: 'dermatology', label: 'Dermatology' },
  { value: 'emergency', label: 'Emergency Medicine' },
  { value: 'family', label: 'Family Medicine' },
  { value: 'internal', label: 'Internal Medicine' },
  { value: 'neurology', label: 'Neurology' },
  { value: 'obstetrics', label: 'Obstetrics & Gynecology' },
  { value: 'ophthalmology', label: 'Ophthalmology' },
  { value: 'orthopedics', label: 'Orthopedic Surgery' },
  { value: 'otolaryngology', label: 'Otolaryngology' },
  { value: 'pathology', label: 'Pathology' },
  { value: 'pediatrics', label: 'Pediatrics' },
  { value: 'psychiatry', label: 'Psychiatry' },
  { value: 'radiology', label: 'Radiology' },
  { value: 'surgery', label: 'Surgery' },
  { value: 'urology', label: 'Urology' },
  { value: 'other', label: 'Other' },
]; 